import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    <div className="w-full sticky top-0 left-0 h-16 flex justify-between items-center px-6 bg-primary/60 dark:bg-primary">
                        <h1 className="font-bold">VIDEO / CALL / Chat</h1>
                        <ModeToggle />
                    </div>
                    {children}
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
